apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: spring.nfestatech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: springapp
            port: 
              number: 80
  
